DROP TABLE IF EXISTS TRANSACTION;
CREATE TABLE TRANSACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_VALUE DOUBLE,
    SCHEDULED_DATE TIMESTAMP,
    FEE DOUBLE,
    ACCOUNT_FROM VARCHAR(255),
    ACCOUNT_TO VARCHAR(255)
);